"""Extract MASKS and DIMS from frontend/apt.js into src/collage_data.py.

Run from the project root:
    python3 tools/extract_collage_data.py

This is a one-time build tool. Run whenever MASKS/DIMS are regenerated
by the AvianVisitors pipeline (cutout.py -> build_masks.py).
"""

import json
import re
import sys
from pathlib import Path


def extract_var(text: str, var_name: str) -> str:
    """Extract the JSON value assigned to `var <var_name> = ...;`."""
    m = re.search(rf"var\s+{var_name}\s*=\s*(\{{.+?\}})\s*;", text, re.DOTALL)
    if not m:
        raise ValueError(f"Could not find var {var_name} in input")
    return m.group(1)


def format_python_dict(data, indent: int = 0) -> str:
    """Format a Python dict as compact multi-line code.

    Handles deeply nested dicts with large base64 strings by keeping
    values on single lines.
    """
    pad = " " * indent
    items = []
    for key, value in data.items():
        if isinstance(value, dict) and "bits" in value:
            v = f'{{"w": {value["w"]}, "h": {value["h"]}, "bits": {json.dumps(value["bits"])}}}'
        else:
            v = json.dumps(value, ensure_ascii=False)
        items.append(f"{pad}{json.dumps(key)}: {v}")
    return "{\n" + ",\n".join(items) + "\n" + pad.rstrip() + "}"


def main():
    repo_root = Path(__file__).resolve().parent.parent
    apt_js = repo_root / "frontend" / "apt.js"
    output = repo_root / "src" / "collage_data.py"

    text = apt_js.read_text(encoding="utf-8")

    dims_json = extract_var(text, "DIMS")
    masks_json = extract_var(text, "MASKS")

    dims = json.loads(dims_json)
    masks = json.loads(masks_json)

    print(f"DIMS: {len(dims)} entries")
    print(f"MASKS: {len(masks)} entries")

    lines = [
        "# Auto-generated by tools/extract_collage_data.py",
        "# Do not edit manually. Re-run the extraction script when MASKS/DIMS",
        "# are regenerated by the AvianVisitors pipeline.",
        "",
        "# Dimensions map: slug -> [width, height]",
        "DIMS: dict[str, list[int]] = " + json.dumps(dims, ensure_ascii=False, separators=(",", ":")),
        "",
        "# Mask map: slug -> {w: int, h: int, bits: str}",
        "# bits is base64-encoded binary mask (MSB-first).",
        "MASKS: dict[str, dict] = " + format_python_dict(masks, indent=0),
        "",
    ]

    output.write_text("\n".join(lines), encoding="utf-8")
    print(f"Wrote {output} ({len(dims) + len(masks)} entries)")


if __name__ == "__main__":
    main()